### ISSUE TITLE
When I try to run train.py the attribute error occurs

### ISSUE THREAD

**Issue by harryjhnam** [yufengm/Adaptive#11]
Hello,

When I try to run the 'train.py' there comes this error.

> Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main( args )
  File "train.py", line 176, in main
    cider = coco_eval( adaptive, args, epoch )
  File "/home/harryjhnam/Documents/final_project/Adaptive/utils.py", line 120, in coco_eval
    CocoEvalLoader( args.image_dir, args.caption_val_path, transform ).samples
AttributeError: 'CocoEvalLoader' object has no attribute 'samples'

I have modified your code for python3.5.2 and also tried on the python2.7 with your original code, but both methods occur the same error.

**Comment by xuyu0010** [comment]
Hi, I am also hitting this Attribute Error, any clues on how to solve this? Thank you!

**Comment by wangru26** [comment]
Hi,I also have this problem, have you solved it?Thanks !

**Comment by WWWWWLI** [comment]
I imitate data_loader.py add __len__ function to class CocoEvalLoader which in utils.py
The definition of __len__ function is
`def __len__(self):
        return len(self.imgs)`

**Comment by hyojin-ki** [comment]
@WWWWWLI Hi. I also have this problem, but solved it thanks to you! Thank you!
